<a href="https://colab.research.google.com/github/Rgarlay/PWSkills_Assignments/blob/main/Numpy/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Theory Questions:

###1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


Ans:- Following points highlight how NumPy assists in scientific computing and data analysis.
1.	It parallelizes all calculations that were to be computed sequentially, if done conventionally. This makes computing process much faster.
2.	NumPy itself is built in C language, which is fastest (after C++). Which makes the library itself very fast.
3.	Many of the mathematical functions and processes (linear algebra, matrix manipulation etc.) are coded within library itself, avoiding to define them manually.
4.	NumPy shares compatibility with other libraries like Pandas, tensorflow, Scikit learn and with other data structures like lists, tuples, making it dynamic and convenient to work with.


###2. Compare and contrast `np.mean()` and `np.average()` functions in NumPy. When would you use one over the other?

Ans:- np.mean() calculates the arithmetic mean of the array given.
np.average() calculate the weighted average of the array.
np.mean() does not take weights array for the target array.
np.average() takes weight as an parameter.
Without weights, np.average() is same as np.mean().


In [2]:
import numpy as np
a_1,weights = np.random.randint(1,11,5),np.random.randint(2,5,5)
print(a_1)
print(weights)
print(np.mean(a_1,))
print(np.average(a_1,weights=weights))

[8 1 9 1 4]
[2 2 4 2 2]
4.6
5.333333333333333


###3rd question answered at last.

####4.How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans:- NumPy array, unlike lists, take homogeneous datatypes throughout. Detecting datatype of a single element will give you datatype of all the elements.`print(a[0])`
NumPy also has inbuilt functionality to detect the data types. For that,we can write:
`a.dtype`

Importance of data types: - Not all datatypes take up equal space in the memory. For example, int32 takes 4 bytes and float64 takes 8 bytes. While int64 may have greater range than int32, it is heavier in terms of storage and computation. Small data types take up less time in processing.


In [3]:
a = np.array([1,2,3])
print(type(a[0]))
print(a.dtype)

<class 'numpy.int64'>
int64


####5.Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Ans:- `ndarray` in numpy are N dimensional array that are supported from NumPy library.
Numpy array store homogeneous datatypes. They are optimized for scientific calculation and data analytic objects.

 They support various types of operation such as Dot product multiplication or Linear transformations. They are fast in computation and compatible with a number of libraries and datatypes.

Whereas `list` is an inbuilt data structure/object in python. It supports multiple data types as elements. The time order of execution for list having n elements is O(n). And unlike ndarray, they cannot vectorize the operations for optimizations.


####6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans:- Let’s take a look at example for for list and NumPy handling big data object.

In [6]:
import time

size = 10**6
# Python list
python_list = [i for i in range(size)]
start = time.time()
python_result = [x * 2 for x in python_list]
print("Python List Time:", time.time() - start)

# NumPy array
numpy_array = np.arange(size)
start = time.time()
numpy_result = numpy_array * 2
print("NumPy Array Time:", time.time() - start)


Python List Time: 0.09050226211547852
NumPy Array Time: 0.005393028259277344


Note that the execution time for numpy is orders less than the list. As the complexity of algorithm and data size will increase, so will the difference.
Numpy array makes **computation faster.**

In [11]:
import sys
python_list_size = sum(sys.getsizeof(x) for x in python_list) + sys.getsizeof(python_list)
print("Python List Size (bytes):", python_list_size)

numpy_array_size = numpy_array.nbytes
print("NumPy Array Size (bytes):", numpy_array_size)

Python List Size (bytes): 36448728
NumPy Array Size (bytes): 8000000


This highlights the size difference in list and numpy. Ndarray object takes much less space in memory than list.

####7. Compare `vstack()` and `hstack()` functions in NumPy. Provide examples demonstrating their usage and output.

Ans:- vstack() is a method of NumPy library. This concatenates 2 or more arrays along 1 axis. However, we must note that the number of elements of arrays that we are concatenating must be same.

In [12]:
a = np.array([1,2])
b = np.array([4,3])
c = np.array([5,6])
e = np.array([7,8])

d = np.vstack((a,b,c,e))
print(d)
print(np.shape(a))
print(np.shape(d))


[[1 2]
 [4 3]
 [5 6]
 [7 8]]
(2,)
(4, 2)


hstack() is another method in numpy. This concatenates arrays along the x axis. As the arrays are concatined along axis 0, all elements collapse into a single numpy array of dimension (N,)

In [13]:
a_1 = np.array([1,2])
b_1 = np.array([4,3])
c_1 = np.array([5,6])
e_1 = np.array([7,8])

d_1 = np.hstack((a_1,b_1,c_1,e_1))
print(d_1)
print(np.shape(a_1))
print(np.shape(d_1))


[1 2 4 3 5 6 7 8]
(2,)
(8,)



####8. Explain the differences between `fliplr()` and `flipud()` methods in NumPy, including their effects on various array dimensions.

Ans:- fliplr() is a numpy method. It can flip an array and switch its left column with right columns and reverse the order.
For examples:


In [14]:
b = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.fliplr(b))


[[3 2 1]
 [6 5 4]
 [9 8 7]]


This share allot of similarities with the fliplr(), except that it flips vertically and fliplr() flips horizontally.
fliplr() takes a minimum of 2 dimensional array in its input and flips it out.
If the number of columns are even, then inside columns are also flipped with their respective counterparts.


In [15]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.flipud(a))


[[7 8 9]
 [4 5 6]
 [1 2 3]]


####9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans: - narray_split() is a NumPy method that splits the array into the specified number of sub arrays.
For example: -


In [16]:
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr[0])


[[1 2]
 [3 4]]


If the number of sub-array specified cannot inherit equal amount of arrays, then the last array will receive an extra element.

####10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Ans:- Broadcasting explains how numpy treats array during simple arithmetic operations.
When 2 array are operated on with the arithmetic operator, It expands the smaller array to match the dimension of the larger array to ease up the process.


In [18]:
Arr,b  = np.array([1,2,3]) ,10
C= Arr + b
print(C)

[11 12 13]


When 2 array are operated on with the arithmetic operator, It expands the smaller array to match the dimension of the larger array to ease up the process.
Consider another examples:



In [19]:
a_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b_1 = np.array([2,5,8])
c_1 = a_1*b_1
print(c_1)

[[ 2 10 24]
 [ 8 25 48]
 [14 40 72]]


Notice that, element wise multiplication is performed, despite the arrays being of different dimensions. This is possible, because numpy broadcasts the smaller array to match with the larger array.
Note that: The smaller array must have the same number of dimension as larger one.
For example:


In [20]:
a_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
b_2 = np.array([2,5,8,4])
c_2 = a_1*b_1
print(c_2)


[[ 2 10 24]
 [ 8 25 48]
 [14 40 72]]


This raises an error, as there’s no dimensional consistency on how to expand b_2.

**Vectorization** refers to process of performing operation of entire arrays without explicit loops. Instead of iterationg, we can just operate on the entire array at once.
This improves the speed of operation, makes our code more concise.


In [24]:
##Without using vectorization
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.add(a, b)
print(result)
# Vectorized addition
result_1 = a + b
print(result_1)


[5 7 9]
[5 7 9]


####3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

In [25]:
#To reverse an array, we can employe indexing.
#1D example:
A = np.array([1,2,3,4])
A_1 = np.array([[1,2,3],[4,5,6]])

A_reversed = A[::-1]
print(A_reversed)
A_1_rows_reversed = A_1[:,::-1]
A_1_reversed = A_1_rows_reversed[::-1,:]
print(A_1_reversed)


[4 3 2 1]
[[6 5 4]
 [3 2 1]]


Hence, we can be reverse array of any dimension (one dimension per iteration) using this method.
Also, for any array>1D, we can use flipud() and fliplr() to reverse the matrix. Examples are given above in question 8.


# Practical Questions

####1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [31]:
a = np.random.randint(1,100,size=(3,3))


In [34]:
print(a)

[[20 45 15]
 [39 96 91]
 [53 46 59]]


In [35]:
## To interchange rows with columns
a = a.T
print(a)

[[20 39 53]
 [45 96 46]
 [15 91 59]]


####2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [38]:
a_1 = np.random.randint(1,100,size = (2,5))
print(a_1)

[[28  9 23 64 20]
 [27 52 80 60 40]]


In [39]:
##To convert it into 5x2
print(a_1.T)

[[28 27]
 [ 9 52]
 [23 80]
 [64 60]
 [20 40]]


####3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [49]:
b = np.random.rand(4,4)


In [50]:
print(b)

[[0.96713025 0.50182912 0.71965642 0.37977443]
 [0.78390615 0.15196521 0.72191851 0.71459166]
 [0.7694637  0.81644091 0.25901964 0.95703174]
 [0.52800996 0.64248925 0.12247542 0.57498424]]


In [54]:
zers = np.zeros((6,6))
zers[:4,:4] = b

In [58]:
print(zers)

[[0.96713025 0.50182912 0.71965642 0.37977443 0.         0.        ]
 [0.78390615 0.15196521 0.72191851 0.71459166 0.         0.        ]
 [0.7694637  0.81644091 0.25901964 0.95703174 0.         0.        ]
 [0.52800996 0.64248925 0.12247542 0.57498424 0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


####4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [61]:
int_arr = np.arange(10,61,5)
int_arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

####5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [85]:
strings_1 = np.array(['python', 'numpy', 'pandas'])

strings_1[0] = np.char.upper(strings_1[0])

strings_1[1] = np.char.lower(strings_1[1])

strings_1[2] = np.char.title(strings_1[2])

strings_1

array(['PYTHON', 'numpy', 'Pandas'], dtype='<U6')

####6.. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [33]:
words = np.array(['apple', 'banana', 'cherry', 'date', 'elderberry'])

words = np.char.join(' ',words)

words


array(['a p p l e', 'b a n a n a', 'c h e r r y', 'd a t e',
       'e l d e r b e r r y'], dtype='<U19')

####7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [35]:
a = np.random.randn(2,2)
b = np.random.randn(2,2)

In [41]:
a+b

array([[ 2.10914294,  2.59935848],
       [ 0.18567435, -1.63658727]])

In [42]:
a*b

array([[ 0.54828134,  1.54034128],
       [-0.01912311,  0.2417158 ]])

In [43]:
a - b

array([[ 1.50178514, -0.77155649],
       [ 0.3331177 , -1.308264  ]])

In [44]:
a/b

array([[ 5.94530609,  0.54222726],
       [-3.51858576,  8.96936507]])

####7. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [45]:
a_5 = np.random.rand(5,5)

In [46]:
a_5

array([[0.79220905, 0.24030679, 0.24737235, 0.89232028, 0.46107907],
       [0.08862999, 0.87672025, 0.23117563, 0.23769025, 0.01007504],
       [0.30670732, 0.65309025, 0.37855075, 0.69263053, 0.99686986],
       [0.33721489, 0.69920026, 0.2071311 , 0.9043602 , 0.82850526],
       [0.44193331, 0.33247465, 0.37079489, 0.39453588, 0.87794969]])

In [56]:
diagonal_elements = np.diag(a_5)
diagonal_elements

array([0.79220905, 0.87672025, 0.37855075, 0.9043602 , 0.87794969])

####9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [59]:
one_thousand = np.random.randint(1,1000,100)

In [60]:
np.size(one_thousand)

100

In [75]:
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

random_array = np.random.randint(0, 1001, 100)

In [76]:
prime_numbers = [num for num in random_array if is_prime(num)]
prime_numbers

[811, 367, 853, 193, 229, 971, 751, 379, 683, 587, 769, 769, 179, 991, 907]

####10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [84]:
daily_temperatures = np.random.uniform(15, 35, 30)

weeks = daily_temperatures[:28].reshape(4, 7)

weekly_averages = weeks.mean(axis=1)

daily_temperatures, weekly_averages

(array([19.58412422, 17.8729473 , 33.2576349 , 28.37906155, 23.75972043,
        26.46519141, 29.9122781 , 30.46063797, 33.39788362, 23.53685578,
        20.8682182 , 27.79328534, 23.31455799, 26.89196908, 23.39971597,
        18.05991573, 24.38853503, 28.81835644, 30.98567615, 24.86652554,
        18.3047578 , 23.29375419, 30.72587858, 23.25718541, 28.93061587,
        25.14427363, 19.8244625 , 30.92301016, 16.68426908, 25.49780566]),
 array([25.60442256, 26.60905828, 24.11764038, 26.01416862]))